# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-06 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_rest', '0002_auto_20161004_1944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apps',
            options={'verbose_name': 'App', 'verbose_name_plural': 'Apps'},
        ),
        migrations.AlterModelOptions(
            name='attachments',
            options={'verbose_name': 'Attachment', 'verbose_name_plural': 'Attachments'},
        ),
        migrations.AlterModelOptions(
            name='email',
            options={'verbose_name': 'Email', 'verbose_name_plural': 'Emails'},
        ),
        migrations.AddField(
            model_name='email',
            name='tag',
            field=models.CharField(default='', max_length=255),
        ),
    ]
