# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-07 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_rest', '0003_auto_20161006_2346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachments',
            old_name='body',
            new_name='path',
        ),
        migrations.AlterField(
            model_name='email',
            name='is_html',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='tag',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
